name: assignment-workflow
on: workflow_dispatch
jobs:
    az-terraform:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4

        -   name: az login
            run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4
        
        -   name: terraform setup
            uses: hashicorp/setup-terraform@v3
        
        -   name: terraform initialize
            run: |
                cd terraform  && terraform init
        
        -   name: validate
            run: |
                cd terraform && terraform validate
        
        -   name: plan
            run: |
                cd terraform && terraform plan
        
        -   name: apply terraform
            run: |
                cd terraform && terraform apply
    
        -   name: destroy
            run: |
                cd terraform && terraform destroy
                