name: assignment-workflow
on: workflow_dispatch
jobs:
    az-terraform:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4

        -   name: az login
            run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4
        
        -   name: terraform setup
            uses: hashicorp/setup-terraform@v3
        
        -   name: terraform initialize
            run: |
                cd terraform  && terraform init
        
        -   name: validate
            run: |
                cd terraform && terraform validate
        
        -   name: plan
            run: |
                cd terraform && terraform plan
        
        -   name: apply terraform
            run: |
                cd terraform && terraform apply -auto-approve
    
        -   name: get cluster and rg name
            run: |
                cd terraform 
                resource_group_name=$(terraform output rg_name)
                cluster_name=$(terraform output aks_name) 
                echo "resource_group_name=$resource_group_name" >> $GITHUB_ENV 
                echo "cluster_name=$cluster_name" >> $GITHUB_ENV

        -   name: accessing aks_cluster
            run: |
                az aks get-credentials --resource-group ${{ ENV.resource_group_name}} --name ${{ ENV.cluster_name}}

        -   name: creating namespace deploying app and service for sql
            run: |
                cd eks-manifests && kubectl create ns assignment
                && kubectl apply -n assignment -f mysql-deployment.yml
                && kubectl apply -n assignment -f mysql-configmap.yml
                && kubectl apply -n assignment -f mysql-secrets.yml
                && kubectl apply -n assignment -f mysql-service.yml
                && kubectl get all -n assignment
                
        -   name: deploying app and its service
            run: |
                cd eks-manifests && kubectl apply -n assignment -f two-tier-app-deployment.yml
                && kubectl apply -n assignment -f two-tier-app-svc.yml
                && kubectl get all -n assignment
                