name: after-workflow-1
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4
        -   name: az credentials
            run: az login --tenant ${{ secrets.tenant_id}}

        -   name: accessing aks_cluster
            run: |
                az aks get-credentials --resource-group k8-rg --name k8-cluster
        
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.docker_username }}
              password: ${{ secrets.docker_password }}
        
        -   name: check docker login
            run: docker info
        
        -   name: build and tag image
            run: |
                IMAGE="${{ secrets.DOCKER_USERNAME }}/assignment"
                docker build -t $IMAGE .
        
        -   name: push docker image
            run: |
                IMAGE="${{ secrets.DOCKER_USERNAME }}/assignment"
                docker push $IMAGE


        -   name: changing k8 manifests sql
            run:  |
                cd k8s
                kubectl apply -n assignment -f mysql-deployment.yml
                kubectl apply -n assignment -f mysql-configmap.yml
                kubectl apply -n assignment -f mysql-secrets.yml
                kubectl apply -n assignment -f mysql-svc.yml                

                        
        -   name: changing k8 manifests app
            run: |
                cd k8s
                kubectl rollout restart deployment two-tier-app -n assignment

                kubectl apply -f two-tier-app-svc.yml -n assignment
              
                kubectl get all -n assignment