name: after-workflow-1
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4
        -   name: az credentials
            run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

        -   name: accessing aks_cluster
            run: |
                az aks get-credentials --resource-group k8-rg --name k8-cluster
        
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.docker_username }}
              password: ${{ secrets.docker_password }}
        
        -   name: check docker login
            run: docker info
        
        -   name: build and tag image
            run: |
                IMAGE_TAG="${GITHUB_SHA}"
                IMAGE="${{ secrets.DOCKER_USERNAME }}/assignment:$IMAGE_TAG"
                docker build -t $IMAGE .
        #        docker tag assignment-image ${{ secrets.docker_username }}/assignment:IMAGE_TAG
        
        -   name: push docker image
            run: |
                IMAGE_TAG="${GITHUB_SHA}"
                IMAGE="${{ secrets.DOCKER_USERNAME }}/assignment:$IMAGE_TAG"
                docker push $IMAGE
         #   run: docker push ${{ secrets.docker_username }}/assignment:IMAGE_TAG

        # -   name: update docker image
       
        #     with:
        #         base-image: ${{ secrets.docker_username }}/asignment:latest
        #         image: ${{ secrets.docker_username }}/asignment:latest

          


        -   name: changing k8 manifests sql
            run:  |
                cd k8s
                kubectl apply -n assignment -f mysql-deployment.yml
                kubectl apply -n assignment -f mysql-configmap.yml
                kubectl apply -n assignment -f mysql-secrets.yml
                kubectl apply -n assignment -f mysql-svc.yml                

        -   name: Replace placeholders with Docker username and tag
            run: |
                sed "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" k8s/two-tier-app-deployment.yml | sed "s|\${IMAGE_TAG}|${GITHUB_SHA}|g" | kubectl apply -f -
                  
                
        -   name: changing image in deployment
            run: |
                IMAGE_TAG="${GITHUB_SHA}"
                export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} 
                export IMAGE_TAG="${GITHUB_SHA}"
                echo "Using image: ${DOCKER_USERNAME}/assignment:${IMAGE_TAG}"
                kubectl set image deployment/two-tier-app two-tier-app=${{ secrets.DOCKER_USERNAME }}/assignment:$IMAGE_TAG 
              #  envsubst < k8s/two-tier-app-deployment.yml | kubectl apply -f -           
        -   name: changing k8 manifests app
            run: |
                cd k8s
                kubectl apply -n assignment -f two-tier-app-deployment.yml
                kubectl apply -n assignment -f two-tier-app-svc.yml                
                kubectl get all -n assignment