name: after-workflow-1
on: workflow_dispatch
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        -   name: get code
            uses: actions/checkout@v4
        -   name: az credentials
            run: az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

        -   name: accessing aks_cluster
            run: |
                az aks get-credentials --resource-group k8-rg --name k8-cluster
        
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.docker_username }}
              password: ${{ secrets.docker_password }}
        
        -   name: check docker login
            run: docker info
        
        -   name: build and tag image
            run: |
                docker build -t assignment-image .
                docker tag assignment-image ${{ secrets.docker_username }}/assignment:first
        
        -   name: push docker image
            run: docker push ${{ secrets.docker_username }}/assignment:first


        -   name: changing k8 manifests sql
            run:  |
                cd k8s
                kubectl apply -n assignment -f mysql-deployment.yml
                kubectl apply -n assignment -f mysql-configmap.yml
                kubectl apply -n assignment -f mysql-secrets.yml
                kubectl apply -n assignment -f mysql-svc.yml                

        -   name: changing k8 manifests app
            run: |
                
                kubectl apply -n assignment -f two-tier-app-deployment.yml
                kubectl apply -n assignment -f two-tier-app-svc.yml                
                kubectl get all -n assignment